import{ Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from './provider'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata:Metadata = {
  title: 'Twitter  Clone',
  description: 'Generated by Twitter',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider
        attribute='class'
        defaultTheme='dark'
        enableSystem
        disableTransitionOnChange
        >
        {children}
        </Provider>
      </body>
    </html>
  )
}
